/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ll
 */
public class Peso_otros_planetas extends javax.swing.JFrame {
int planetas;
double Mercurio=3.7;
double Venus=8.87;
double Tierra;
double Marte=3.7;
double Jupiter=24.8;
double Saturno=10.44;
double Urano=8.7;
double Neptuno=11.15;
double precio_final;
    /**
     * Creates new form NewJFrame
     */
    public Peso_otros_planetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tu_peso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_planetas = new javax.swing.JComboBox<>();
        btn_consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_salida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PESO EN OTRO PLANETA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TU PESO");

        txt_tu_peso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PLANETAS");

        cbo_planetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbo_planetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno" }));
        cbo_planetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_planetasActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_consultar.setText("CONSULTAR");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        txt_salida.setColumns(20);
        txt_salida.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txt_salida.setForeground(new java.awt.Color(0, 0, 255));
        txt_salida.setRows(5);
        jScrollPane1.setViewportView(txt_salida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_planetas, 0, 98, Short.MAX_VALUE)
                                    .addComponent(txt_tu_peso))
                                .addGap(32, 32, 32)
                                .addComponent(btn_consultar))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tu_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_planetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_planetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_planetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_planetasActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
double tupeso = Double.parseDouble(txt_tu_peso.getText());
planetas=cbo_planetas.getSelectedIndex();
       /* if (Planetas==0) {
            precio_final=tupeso*Mercurio;
            txt_salida.setText("Tu peso en MERCURIO es: "+precio_final+"KG");            
        } else {
            if (Planetas==1) {
            precio_final=tupeso*Venus;
            txt_salida.setText("Tu peso en VENUS es: "+precio_final+"KG");
            } else {
                if (Planetas==2) {
            
            txt_salida.setText("Tu peso en TIERRA es: "+tupeso+"KG");
            }
                if (Planetas==3) {
                    precio_final=tupeso*Marte;
                    txt_salida.setText("Tu peso en MARTE es: "+precio_final+"KG");
                } else {
                    if (Planetas==4) {
                       precio_final=tupeso*Jupiter;
                       txt_salida.setText("Tu peso en JUPITER es: "+precio_final+"KG");
                    } else {
                        if (Planetas==5) {
                            precio_final=tupeso*Saturno;
                            txt_salida.setText("Tu peso en SATURNO es: "+precio_final+"KG");
                        } else {
                            if (Planetas==6) {
                                precio_final=tupeso*Urano;
                                txt_salida.setText("Tu peso en URANO es: "+precio_final+"KG");
                            } else {
                                if (Planetas==7) {
                                    precio_final=tupeso*Neptuno;
                                    txt_salida.setText("Tu peso en NEPTUNO es: "+precio_final+"KG");
                                } else {
                                }
                            }
                        }
                    }
                }
        }
        }*/
       
        switch(planetas){
        case 0 : precio_final=tupeso*Mercurio; txt_salida.setText("Tu peso en MERCURIO es: "+precio_final+"KG"); break;
        case 1 : precio_final=tupeso*Venus; txt_salida.setText("Tu peso en VENUS es: "+precio_final+"KG"); break;
        case 2 : precio_final=tupeso; txt_salida.setText("Tu peso en la TIERRA es: "+precio_final+"KG");break;
        case 3 : precio_final=tupeso*Marte; txt_salida.setText("Tu peso en la Marte es: "+precio_final+"KG");break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peso_otros_planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peso_otros_planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peso_otros_planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peso_otros_planetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peso_otros_planetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JComboBox<String> cbo_planetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_salida;
    private javax.swing.JTextField txt_tu_peso;
    // End of variables declaration//GEN-END:variables
}
